#!/usr/bin/env python

import argparse
import re 
from os import path, listdir
from quix.quix import Quix

parser = argparse.ArgumentParser()
parser.add_argument('-f','--file', help='Text file to load into db', default="don-quixote.txt")
parser.add_argument('-d','--db', help='Directory where lveldb files will be created', default="dqdb")

args = parser.parse_args()

dq = Quix(db_path=args.db, text_path=args.file)

fragment = dq.generate_fragment()
pattern = re.compile(fragment)

base = path.split(args.file)[0]
chapter = ""

for file in listdir(base):
    if file.startswith("Book"):
        with open(path.join(base, file)) as f:
            if fragment in f.read():
                chapter = file.split(".")[0]

print(f"From {chapter}")
print("--------------------------")
print(fragment)
